name: Build images
on: push

jobs:
    build:
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                name: ['cpp']
        steps:
            - uses: actions/checkout@v2
            - name: login to Docker Hub
              if: github.repository == 'judge2020/vs-docker'
              run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u judge2020vsdocker --password-stdin
            - name: Build images
              env:
                NODE: ${{ matrix.node }}
              run: |
                docker build -t base -f base.Dockerfile .
                docker build -t ${{ matrix.name }} -f ${{ matrix.name }}.Dockerfile .
            - name: Push images
              if: github.repository == 'judge2020/vs-docker'
              run: |
                docker tag ${{ matrix.name }} judge2020/vs-docker:${{ matrix.name }}
                docker tag ${{ matrix.name }} judge2020/vs-docker:${{ matrix.name }}-$([int][double]::Parse((Get-Date -UFormat %s)))
                docker push judge2020/vs-docker
